version: "3"

services:
  prestashop:
    image: prestashop/prestashop:8-apache
    environment:
      - DB_SERVER=db_presta
      - DB_NAME=prestashop
      - DB_USER=Tristan
      - DB_PASSWD=P@ssw0rd!
      - PS_DEV_MODE=1
      - PS_DEMO_MODE=1
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8080
      - PS_FOLDER_ADMIN=admin
      - ADMIN_MAIL=demo@prestashop.com
      - ADMIN_PASSWD=prestashop_demo
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - prestashop-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "172.16.1.99:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=tristan_presta
      - MYSQL_PASSWORD=P@ssw0rd!
    networks:
      - prestashop-net

networks:
  prestashop-net:
